// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXTnmPO8g6FkAejAWwEZdwNHrObq_wwOo',
    appId: '1:773602884029:web:80a204ee006c2d1300bad4',
    messagingSenderId: '773602884029',
    projectId: 'flutter-chat-app-52c62',
    authDomain: 'flutter-chat-app-52c62.firebaseapp.com',
    storageBucket: 'flutter-chat-app-52c62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyt6vyY-Ysm6etOr1r-g4DRAmzGIbR2k8',
    appId: '1:773602884029:android:c81d4e4b665d427000bad4',
    messagingSenderId: '773602884029',
    projectId: 'flutter-chat-app-52c62',
    storageBucket: 'flutter-chat-app-52c62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZu4IcOyZTbGDHe9gXUqCiZG2YUOI-oHc',
    appId: '1:773602884029:ios:0c91146e814e349d00bad4',
    messagingSenderId: '773602884029',
    projectId: 'flutter-chat-app-52c62',
    storageBucket: 'flutter-chat-app-52c62.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
